---
driver:
  name: kitchen-azure

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[azure::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
